"""deploy_api.py — upload the Meridian mock API (+ tile assets when present) to Hostinger.

Credentials are NEVER in the repo: key=value file at CREDS_FILE (host/user/password/remote_dir,
optional port) — same file the other NICE demo deploys use. Remote folder mock_api_meridian/ is
created as a sibling of the existing mock_api folders.
"""
import ftplib
import os
import sys
import time

try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

CREDS_FILE = r'C:\Users\jstueck\Downloads\v246_work\mockapi_creds.txt'
GEMINI_KEY_FILE = r'C:\Users\jstueck\Downloads\v246_work\gemini_key.txt'   # → gen_key.txt server-side, NEVER in repo
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   # repo root

FILES = [
    os.path.join(HERE, 'api', 'meridian_api.php'),
    os.path.join(HERE, 'api', 'meridian_customers.php'),
    os.path.join(HERE, 'api', 'meridian_xapp.php'),
    os.path.join(HERE, 'api', 'meridian_image.php'),            # generative hero images (Gemini)
    os.path.join(HERE, 'tile', 'meridian_copilot_tile.html'),   # SKIPped until the tile lands
    os.path.join(HERE, 'tile', 'meridian_tile.js'),             # generated by the builder later
]

# static product shots served from img/ (repo: api/img/*.png|jpg)
IMG_DIR = os.path.join(HERE, 'api', 'img')

NEW_FOLDER = 'mock_api_meridian'


def load_creds():
    if not os.path.exists(CREDS_FILE):
        sys.exit('ERROR: credentials file not found at:\n  ' + CREDS_FILE +
                 '\nCreate it per the deploy-mockapi skill (host/port/user/password/remote_dir).')
    creds = {}
    with open(CREDS_FILE, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            k, v = line.split('=', 1)
            creds[k.strip()] = v.strip()
    for k in ('host', 'user', 'password', 'remote_dir'):
        if k not in creds:
            sys.exit('ERROR: creds file missing key: ' + k)
    creds.setdefault('port', '21')
    parent = creds['remote_dir'].rstrip('/').rsplit('/', 1)[0] + '/'
    creds['base_dir'] = parent
    creds['target_dir'] = parent + NEW_FOLDER + '/'
    return creds


def deploy(creds):
    print('=' * 70)
    print('deploy_api (Meridian)  ->  ' + creds['host'] + creds['target_dir'])
    print('=' * 70)
    try:
        ftp = ftplib.FTP()
        ftp.connect(creds['host'], int(creds['port']), timeout=20)
        ftp.login(creds['user'], creds['password'])
        ftp.set_pasv(True)
        print('  connected ✓')
    except Exception as e:
        sys.exit('  connection FAILED: ' + str(e))

    try:
        ftp.cwd(creds['base_dir'])
    except Exception as e:
        ftp.quit(); sys.exit('  cwd base FAILED: ' + str(e))
    try:
        ftp.cwd(NEW_FOLDER)
        print('  cd ' + creds['target_dir'] + ' ✓ (existing)')
    except Exception:
        try:
            ftp.mkd(NEW_FOLDER)
            ftp.cwd(NEW_FOLDER)
            print('  created + cd ' + creds['target_dir'] + ' ✓')
        except Exception as e:
            ftp.quit(); sys.exit('  mkd/cwd FAILED: ' + str(e))

    ok = failed = skipped = 0
    for local_path in FILES:
        name = os.path.basename(local_path)
        if not os.path.exists(local_path):
            print('  - ' + name + '  SKIP (not found)'); skipped += 1; continue
        size_str = '%.1f KB' % (os.path.getsize(local_path) / 1024.0)
        t0 = time.time()
        try:
            with open(local_path, 'rb') as f:
                ftp.storbinary('STOR ' + name, f)
            print('  ✓ ' + name.ljust(30) + size_str.rjust(10) + '  in %.1fs' % (time.time() - t0))
            ok += 1
        except Exception as e:
            print('  ✗ ' + name + '  FAILED: ' + str(e)); failed += 1

    # ---- Gemini key (server name gen_key.txt) — from the secrets folder, never the repo ----
    if os.path.exists(GEMINI_KEY_FILE):
        try:
            with open(GEMINI_KEY_FILE, 'rb') as f:
                ftp.storbinary('STOR gen_key.txt', f)
            print('  ✓ gen_key.txt (from local secrets folder)')
            ok += 1
        except Exception as e:
            print('  ✗ gen_key.txt  FAILED: ' + str(e)); failed += 1
    else:
        print('  - gen_key.txt  SKIP (no ' + GEMINI_KEY_FILE + ' — image generation will error honestly)')
        skipped += 1

    # ---- static product shots → img/ ----
    if os.path.isdir(IMG_DIR):
        try:
            ftp.mkd('img')
        except Exception:
            pass
        for fn in sorted(os.listdir(IMG_DIR)):
            if not fn.lower().endswith(('.png', '.jpg', '.jpeg', '.webp')):
                continue
            try:
                with open(os.path.join(IMG_DIR, fn), 'rb') as f:
                    ftp.storbinary('STOR img/' + fn, f)
                print('  ✓ img/' + fn)
                ok += 1
            except Exception as e:
                print('  ✗ img/' + fn + '  FAILED: ' + str(e)); failed += 1

    # ---- gen/ cache dir for meridian_image.php (PHP can also mkdir, this is belt+braces) ----
    try:
        ftp.mkd('gen')
    except Exception:
        pass

    ftp.quit()
    print('=' * 70)
    print('  uploaded: %d   skipped: %d   failed: %d' % (ok, skipped, failed))
    web_path = creds['target_dir'].replace('/public_html/aicoe', '')
    base_url = 'https://aicoe.3ddesignview.com' + web_path
    print('  mock-API:  ' + base_url + 'meridian_api.php?action=ping')
    print('=' * 70)
    if failed:
        sys.exit(1)


if __name__ == '__main__':
    deploy(load_creds())
